# Generated by Django 4.1.7 on 2023-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('coments', models.CharField(max_length=350)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
