# Generated by Django 4.1.7 on 2023-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactoprincipal',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
