# Generated by Django 4.1.7 on 2023-02-19 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import nlibros.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('photo_libro', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('estado_libro', models.CharField(choices=[('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy_bueno', 'Muy Bueno'), ('Excelente', 'Excelente')], max_length=100)),
                ('genero_libro', models.CharField(max_length=100)),
                ('puntuacion', nlibros.models.RangeIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('tiempo_devolucion', models.CharField(max_length=110)),
                ('cantidad_paginas', models.IntegerField()),
                ('unidades_disponibles', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
