# Generated by Django 4.1.7 on 2023-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlibros', '0002_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
