# Generated by Django 4.1.7 on 2023-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlibros', '0003_alter_product_puntuacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='autor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad_paginas',
            field=models.IntegerField(blank=True, max_length=2500),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='puntuacion',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tiempo_devolucion',
            field=models.CharField(blank=True, max_length=110),
        ),
        migrations.AlterField(
            model_name='product',
            name='unidades_disponibles',
            field=models.IntegerField(blank=True),
        ),
    ]
