# Generated by Django 4.1.7 on 2023-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlibros', '0004_alter_product_autor_alter_product_cantidad_paginas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cantidad_paginas',
            field=models.IntegerField(blank=True),
        ),
    ]
